env:
  RUBY_VERSION: 2.7.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

name: Workflow
on: [pull_request]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Check code
        run: bundle exec rubocop
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: brakeman report
        run: |
          bundle exec brakeman
  rspec-test:
    name: RSpec
    needs: [rubocop-test, brakeman]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install jq for JSON parsing
        run: sudo apt-get install jq
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Create database
        run: |
          cp spec/dummy/config/database.yml.github-actions spec/dummy/config/database.yml
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          resultPath: coverage/.last_run.json
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: 100
      - name: Find Test Coverage %
        run: |
          echo "TEST_COVERAGE=$(echo "`cat coverage/.last_run.json | jq -r .result.line`")" >> $GITHUB_ENV
        id: find-test-coverage
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.5.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: be2fa5413124206272dbc700f3201f5a
          filename: db_blaster__${{ github.event.pull_request.head.ref }}.json
          label: Test Coverage
          message: ${{ env.TEST_COVERAGE }}%
          color: green

